version: '3.7'

services:
  app:
    container_name: app
    hostname: app
    build:
      context: .
      target: development
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run start:prod
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    hostname: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080